{{ if .Values.grafana.create }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: {{ .Values.grafana.targetRevision }}
    chart: grafana
    helm:
      values: |
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
            - name: Prometheus
              type: prometheus
              url: http://prometheus-server.prometheus.svc.cluster.local
              access: proxy
              isDefault: true
        dashboards:
          default:
            nginx-ingress:
              gnetId: 9614
              revision: 2
              datasource: Prometheus
            storage:
              gnetId: 11455
              revision: 6
              datasource: Prometheus
            cpu-memory:
              gnetId: 15661
              revision: 1
              datasource: Prometheus
        {{ if .Values.grafana.adminUser.keySet }}
        admin:
          ## Name of the secret. Can be templated.
          existingSecret: {{ .Values.grafana.adminUser.secretId }}
          userKey: {{ .Values.grafana.adminUser.usernameKey }}
          passwordKey: {{ .Values.grafana.adminUser.passwordKey }}
        {{ end }}
  destination: 
    server: https://kubernetes.default.svc
    namespace: grafana
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
{{ end }}