{{ if .Values.grafana.create }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: {{ .Values.grafana.targetRevision }}
    chart: grafana
    helm:
      values: |
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
            - name: Prometheus
              type: prometheus
              url: http://prometheus-server.prometheus.svc.cluster.local
              access: proxy
              isDefault: true
        {{ if .Values.grafana.local }}
        adminPassword: admin
        {{ end }}
  destination: 
    server: https://kubernetes.default.svc
    namespace: grafana
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
{{ end }}