apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-grafana
  namespace: grafana
spec:
  rules:
  - host: grafana.{{ .Values.grafana.domainName }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: grafana-server
            port:
              number: grafana-server
  ingressClassName: nginx