{{ if .Values.grafana.create }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
spec:
  project: default
  source:
    repoURL: https://wiremind.github.io/wiremind-helm-charts
    targetRevision: {{ .Values.grafana.targetRevision }}
    chart: kube-prometheus-stack-crds
  destination: 
    server: https://kubernetes.default.svc
    namespace: grafana
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - Replace=true
    automated:
      selfHeal: true
      prune: true
{{ end }}