apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-argocd
  namespace: argocd
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: argocd.{{ .Values.ingress.domainName }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              number: 80
  ingressClassName: nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-argo-workflows
  namespace: argo-workflows
spec:
  rules:
  - host: argo-workflows.{{ .Values.ingress.domainName }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argo-workflows-server
            port:
              number: 2746
  ingressClassName: nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-airflow
  namespace: airflow
spec:
  rules:
  - host: airflow.{{ .Values.ingress.domainName }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: airflow-webserver
            port:
              name: airflow-ui
  ingressClassName: nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-jupyterhub
  namespace: jupyterhub
spec:
  rules:
  - host: jupyterhub.{{ .Values.ingress.domainName }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hub
            port:
              name: hub
  ingressClassName: nginx