apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL:  https://kubernetes.github.io/ingress-nginx
    targetRevision: {{ .Values.nginx.targetRevision }}
    chart: ingress-nginx
    helm:
      values: |
        {{ if .Values.airflow.local }}
        controller:
          hostPort:
            enabled: true
          service:
            type: NodePort
          nodeSelector:
            ingress-ready: "true"
        {{ end }}
  destination: 
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true