apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-prometheus
  namespace: prometheus
spec:
  rules:
  - host: prometheus.{{ .Values.prometheus.domainName }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prometheus-server
            port:
              name: prometheus-server
  ingressClassName: nginx