{{ if .Values.airbyte.create }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airbyte
  namespace: {{ .Values.namespace }}
spec:
  project: default
  source:
    repoURL: https://airbytehq.github.io/helm-charts
    targetRevision: {{ .Values.airbyte.targetHelmChartRevision }}
    chart: airbyte
    helm:
      version: v3
      values: |
        webapp:
          service:
            type: {{ .Values.airbyte.webapp.service.type }}
  destination: 
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespace }}
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
{{ end }}