{{ if .Values.argoWorkflows.create }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: compute-plane
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: {{ .Values.argoWorkflows.targetHelmChartRevision }}
    chart: argo-workflows
    helm:
      values: |
        server:
          extraArgs:
          - --auth-mode=server
          serviceAnnotations:
            "beta.cloud.google.com/backend-config" : "{\"default\": \"{{ .Values.gcp.iap.backendConfigName }}\"}"
  destination: 
    server: https://kubernetes.default.svc
    namespace: compute-plane
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
{{ end }}