{{ if .Values.argoWorkflows.create }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: {{ .Values.namespace }}
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: {{ .Values.argoWorkflows.targetHelmChartRevision }}
    chart: argo-workflows
    helm:
      values: |
        controller:
          workflowNamespaces: {{ .Values.namespace }}
        server:
          extraArgs:
          - --auth-mode=server
          {{ if .Values.gcp.iap.enabled }}
          serviceAnnotations:
            "beta.cloud.google.com/backend-config" : "{\"default\": \"{{ .Values.gcp.iap.backendConfigName }}\"}"
          {{ end }}
  destination: 
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespace }}
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
{{ end }}