apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-argo-workflows
  namespace: argo-workflows
spec:
  rules:
  - host: argo-workflows.{{ .Values.argoWorkflows.domainName }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argo-workflows-server
            port:
              number: 2746
  ingressClassName: nginx