apiVersion: v1
kind: Secret
metadata:
  name: argo-server-sso
  namespace: argo-workflows
type: Opaque
data:
  client-id: {{ .Values.secrets.clientId }}
  client-secret: {{ .Values.secrets.clientSecret }}