apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-system
  namespace: argocd
spec:
  project: default
  source:
    repoURL:  https://istio-release.storage.googleapis.com/charts
    targetRevision: {{ .Values.istio.targetRevision }}
    chart: base
  destination: 
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingress
  namespace: argocd
spec:
  project: default
  source:
    repoURL:  https://istio-release.storage.googleapis.com/charts
    targetRevision: {{ .Values.istio.targetRevision }}
    chart: gateway
  destination: 
    server: https://kubernetes.default.svc
    namespace: istio-ingress
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true