{{ if .Values.airflow.create }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://airflow.apache.org/
    targetRevision: {{ .Values.airflow.targetRevision }}
    chart: airflow
    helm:
      version: v3
      valueFiles:
      - values.yaml
      # Fix for ArgoCD: https://github.com/apache/airflow/pull/16331#issuecomment-857004828
      # Liveliness probe for scheduler: https://github.com/apache/airflow/discussions/20010
      values: |
        {{ if .Values.airflow.local }}
        executor: LocalExecutor
        postgresql:
          enabled: true
          persistence:
            enabled: false
        flower:
          enabled: false
        redis:
          enabled: false
        statsd:
          enabled: false
        pgbouncer:
          enabled: false
        workers:
          resources:
            limits:
              memory: 128Mi
        scheduler:
          livenessProbe:
            initialDelaySeconds: 60
            timeoutSeconds: 120
            failureThreshold: 10
            periodSeconds: 120
          extraVolumes:
            - name: dags
              hostPath:
                path: {{ .Values.airflow.mountConfig.local.dagMountPath }}
                type: Directory
          extraVolumeMounts:
            - name: dags
              mountPath: /opt/airflow/dags
        {{ else }}
        executor: KubernetesExecutor
        {{ end }}
        migrateDatabaseJob:
          jobAnnotations:
            "argocd.argoproj.io/hook": Sync
            "argocd.argoproj.io/sync-wave": "0"
            "argocd.argoproj.io/hook-delete-policy": BeforeHookCreation,HookSucceeded
  destination: 
    server: https://kubernetes.default.svc
    namespace: airflow
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
{{ end }}