apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spark-operator-extra-bindings
  namespace: compute-plane
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spark-operator
subjects:
  {{- range .Values.extraServiceAccounts }}
  - kind: {{ .kind }}
    name: {{ .name }}
    namespace: {{ .namespace }}
  {{- end }}