{{ if .Values.spark.create }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark
  namespace: {{ .Values.namespace }}
spec:
  project: default
  source:
    repoURL: https://googlecloudplatform.github.io/spark-on-k8s-operator
    targetRevision: {{ .Values.spark.targetHelmChartRevision }}
    chart: spark
  destination: 
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespace }}
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
{{ end }}