{{ if .Values.superset.create }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: superset
  namespace: {{ .Values.namespace }}
spec:
  project: default
  source:
    repoURL: http://apache.github.io/superset/
    targetRevision: {{ .Values.superset.targetHelmChartRevision }}
    chart: superset
    helm:
      values: |
        service:
          {{ if .Values.local.enabled }}
          type: NodePort
          {{ end }}
          {{ if .Values.gcp.iap.enabled }}
          serviceAnnotations:
            "beta.cloud.google.com/backend-config" : "{\"default\": \"{{ .Values.gcp.iap.backendConfigName }}\"}"
          {{ end }}
  destination: 
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespace }}
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
{{ end }}