{{ if .Values.jupyterhub.create }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jupyterhub
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://jupyterhub.github.io/helm-chart/
    targetRevision: {{ .Values.jupyterhub.targetHelmChartRevision }}
    chart: jupyterhub
    helm:
      values: |
        ingress:
          enabled: true
          hosts:
            - jupyterhub.{{ .Values.jupyterhub.domainName }}
          ingressClassName: nginx
        proxy:
          service:
            type: ClusterIP
  destination: 
    server: https://kubernetes.default.svc
    namespace: jupyterhub
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
{{ end }}