{{ if .Values.jupyterhub.create }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jupyterhub
  namespace: {{ .Values.namespace }}
spec:
  project: default
  source:
    repoURL: https://jupyterhub.github.io/helm-chart/
    targetRevision: {{ .Values.jupyterhub.targetHelmChartRevision }}
    chart: jupyterhub
    helm:
      values: |
        proxy:
          service:
            type: ClusterIP
            annotations:
              "beta.cloud.google.com/backend-config" : "{\"default\": \"{{ .Values.gcp.iap.backendConfigName }}\"}"
  destination: 
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespace }}
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
{{ end }}