{{ if .Values.jupyterhub.create }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jupyterhub
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://jupyterhub.github.io/helm-chart/
    targetRevision: {{ .Values.jupyterhub.targetRevision }}
    chart: jupyterhub
  destination: 
    server: https://kubernetes.default.svc
    namespace: jupyterhub
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
{{ end }}