airflow:
  create: true
  targetRevision: 1.7.0
  local: true
  mountConfig:
    local:
      dagMountPath: "/home/jered/workplace/team-engineering/airflow/dags" # TODO Change
    github:
      repoUrl: ""
