airflow:
  create: true
  targetRevision: 1.7.0
  local: true
  mountConfig:
    local:
      # This is the mount path on the host node. For `kind`, it is set in the Cluster config. EX:
      #     extraMounts:
      #     - hostPath: /home/jered/workplace/team-engineering/airflow/dags
      #     containerPath: /mnt/airflow/dags
      # See: https://kind.sigs.k8s.io/docs/user/configuration/#extra-mounts for more info.
      dagMountPath: /mnt/airflow/dags
    github:
      repoUrl: ""
  domainName: test.org
