airflow:
  create: true
  targetRevision: 1.7.0
  local: true
  mountConfig:
    local:
      dagMountPath: /mnt/airflow/dags # created this folder at C:\dags -- TODO Change
    github:
      repoUrl: ""
  domainName: test.org
