airflow:
  create: true
  targetHelmChartRevision: 1.7.0
  # Flag for local development. Used to determine some settings that are applied to local clusters only
  # for testing purposes. Otherwise, Airflow likes to consume lots of resources with unneeded processes!
  local:
    enabled: true
  mountConfig:
    local:
      # This is the mount path on the host node. For `kind`, it is set in the Cluster config. EX:
      #     extraMounts:
      #     - hostPath: /home/jered/workplace/team-engineering/airflow/dags
      #     containerPath: /mnt/airflow/dags
      # See: https://kind.sigs.k8s.io/docs/user/configuration/#extra-mounts for more info.
      dagMountPath: /mnt/airflow/dags
    #Github repo URL where DAGs are located. DAGs are mounted as a sidecar & polled periodically for changes.
    github:
      repoUrl: ""
      branch: "master"
      rev: "HEAD"
      dagsPath: "airflow/dags"
      syncInterval: 20
  # Image to use for Airflow.
  # This image defaults to the one managed by Airflow.
  # This should be changed if using custom `requirements.txt` files for your workloads.
  image:
    repository: ~
    tag: ~
  secret: []
  # - envName: ""
  #   secretName: ""
  #   secretKey: ""
gcp:
  enabled: false
  iap:
    enabled: false
    backendConfigName: iap-config
namespace: compute-plane