{{ if .Values.argoEvents.create }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: {{ .Values.argoEvents.targetHelmChartRevision }}
    chart: argo-events
  destination: 
    server: https://kubernetes.default.svc
    namespace: argo-events
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
{{ end }}