{{ if .Values.mlFlow.create }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: {{ .Values.namespace }}
spec:
  project: default
  source:
    repoURL: https://community-charts.github.io/helm-charts
    targetRevision: {{ .Values.mlFlow.targetHelmChartRevision }}
    chart: mlflow
    helm:
      values: |
        service:
          {{ if .Values.local.enabled }}
          type: NodePort
          {{ end }}
          {{ if .Values.gcp.iap.enabled }}
          serviceAnnotations:
            "beta.cloud.google.com/backend-config" : "{\"default\": \"{{ .Values.gcp.iap.backendConfigName }}\"}"
          {{ end }}
  destination: 
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespace }}
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
{{ end }}